Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Metrics/CyclomaticComplexity:
  Enabled: false
  EnforcedStyle: never
Style/NumericLiterals:
  EnforcedStyle: never
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Layout/LineLength:
  Max: 200
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
